# Generated by Django 4.2.1 on 2023-06-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliotech", "0002_alter_author_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="file_number",
            field=models.IntegerField(),
        ),
    ]
