# Generated by Django 4.2.1 on 2023-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliotech", "0003_alter_employee_file_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lendbook",
            name="return_date",
            field=models.DateTimeField(),
        ),
    ]
