# Generated by Django 4.2.1 on 2023-06-07 19:41

import bibliotech.models.book
import bibliotech.models.member
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliotech", "0005_alter_lendbook_lend_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.IntegerField(
                error_messages={"unique": "Ya existe un libro con este ISBN."},
                unique=True,
                validators=[bibliotech.models.book.validate_isbn],
            ),
        ),
        migrations.AlterField(
            model_name="lendbook",
            name="lend_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="lendbook",
            name="return_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(
                validators=[bibliotech.models.member.validate_birth_date]
            ),
        ),
    ]
